### ISSUE TITLE
missing ember-in-viewport

### ISSUE THREAD

**Issue by davidbilling** [ember-infinity/ember-infinity#256]
Getting error missing "ember-in-viewport" if you don't have it installed already in your app.

Probably just change
"ember-in-viewport": "github:DockYard/ember-in-viewport",
to
"ember-in-viewport": "^2.2.0",

in package.json =)

**Comment by snewcomer** [comment]
@davidbilling Yeah we should point to a tagged version now.  Curious - Does your build not allow for pkgs from master/unapproved pkgs?  Or is this just on your own machine?  Maybe try `nombom`? 

Would accept a PR if you would like!  Otherwise I can.

**Comment by davidbilling** [comment]
@snewcomer It is on my machine, will try nombom. I'm not sure when I have time to do it, if you do any other commit I think it will be faster for you to do it. =)  Thanks!

**Comment by snewcomer** [comment]
fixed!  Thanks!

**Comment by davidbilling** [comment]
@snewcomer Thanks! =)

**Comment by davidbilling** [comment]
@snewcomer Sorry I was wrong, still not working. It must be under "dependencies" and not "devdependencies" to be installed in others apps... Should I open a new error?

**Comment by snewcomer** [comment]
Yeah it would be nice if I checked out my branch that uses this addon and made sure it was passing
 👐 🌵   Fixed on master w/ `1.0.0-alpha.8`.  Thanks for pointing this out!
